name: 'marketing_and_sales_funnel_analysis'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  marketing_and_sales_funnel_analysis:
    +schema: s_nishantsingh

    staging:
      +materialized: view

    marts:
      +materialized: table

      marketing:
        +materialized: table

      ecommerce:
        +materialized: table
